[package]
name = "rust-redis"
version = "0.1.0"
authors = ["Jason Ish <jason.ish@oisf.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
#suricata = { path = "../suricata/review/rust", package = "suricata" }
suricata = { version = "7.0.0-alpha", package = "suricata" }
anyhow = "1.0.40"
redis = { version = "0.20.1" }
