[package]
name = "rust-redis"
version = "0.1.0"
authors = ["Jason Ish <jason.ish@oisf.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.40"
redis = { version = "0.20.1" }
#suricata = "7.0.0-dev"
suricata = { path = "../suricata/review/rust" }
